### ISSUE TITLE
QualityOfBathymetricData vs. QualityOfSurveyCoverage

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#13]
_QualityOfBathymetricData_ is defined in the GI Registry as “An area within which a uniform assessment of the quality of the bathymetric data exists.” That definition may be misleading for the "cell-wise quality" dataset (nominally _QualityOfSurveyCoverage_ in the S-102 draft of December 2022), which provides information at the level of individual cells.

A solution would be to have a new type: 
- Name: _QualityOfSurveyCoverage_  or _QualityOfBathymetryCoverage_ or ...(?)
- Definition: _A set of references to value records that provide localised information about depths, uncertainties, and survey metadata_.
- Remark: (none?)

It can be proposed to the GI Registry after the S-102 team discusses, refines, and approves the name and definition, presumably at the next PT meeting.

It should be a (meta-)feature type like QoBD.

**Comment by RohdeBSH** [comment]
Hello @rmalyankar 

The name QualityOfSurveyCoverage comes from the BSH prototype. This name was never intended to be included in the official standard.
There is an agreement between BSH and NOAA. Both organizations have bilaterally agreed to collaborate on the development of the new coverage for the metadata. The division of work has been such that BSH makes the changes to S-100 that are fundamentally necessary, and on that basis, NOAA brings a proposal for use in S-102. Therefore, the names for the S-102 have to be based on the NOAA proposal and not on the test data / prototype data that you got from BSH on 10/11/2022.

We totally agree with you that there needs to be a new feature in the GI Registry.
From our point of view, we would also consider whether the best variant of the new feature would be a combination of QualityOfSurvey and QualityOfBathymetricData.
In general, however, BSH can put all its information in the NOAA proposal. The only important thing is that the attributes of the new feature are mostly optional. We had already explained this in Monaco in December 2022. For example, BSH does not have any information on sensor qualities because we do not measure many data ourselves, but are supplied by other authorities or the port operators.

The description you suggested is okay from our point of view.

**Comment by rmalyankar** [comment]
To summarize the options:
1. Use _QualityOfBathymetricData_, notwithstanding the current definiton in the GI Registry.
2. Define a new feature concept (Q of Survey Coverage or  Q of BathymetryCoverage or ...). This will be proposed to the GI Registry. The registry approval process will take approximately two months. If this alternative is accepted, the S-102 PT should ideally endorse a definition at this week's meeting so registry submission can proceed.

**Comment by rmalyankar** [comment]
Additional consideration: The _Definition_ and _Remarks_ in the feature catalogue will be what mariners see if they look for explanations of features (and attributes). The feature catalogue in turn gets them from the GI Registry.

**Comment by rmalyankar** [comment]
The draft Edition 2.2.0 (20 March 2023) is provisionally using the existing registered feature name QualityOfSurvey as suggested by the Registry Manager.  Proposal for new Registry concept TBD.

**Comment by hasel001** [comment]
Now that version 2.2.0 is submitted to S100WG, we should turn our attention to submitting a proposal to the IHO GI Registry for a new term here as we have previously discussed.

The following was composed by @rmalyankar and has my support:

* * *
Name: QualityOfBathymetryCoverage
Definition: A set of references to value records that provide localised information about depth, uncertainties, and bathymetry coverage metadata.
Remark: The information can be localised down to the level of individual spatial elements in a coverage, such as individual grid cells in a bathymetry grid.
* * *

_Note: An alternative name "QualityOfSurveyCoverage" has also been mentioned, and @rmalyankar has indicated that he has no objection to it._

What do the PT members think of the proposed definition? Once we arrive at a consensus, I will submit our proposal to the Registry.

Thanks!

**Comment by poseiron01** [comment]
Hi!
SMA can support the proposal composed by @rmalyankar with the name: QualityOfBathymetryCoverage
Perhaps it could be good to reach consensus on this topic as soon as possible so we can get things moving at the Registry.

**Comment by rmalyankar** [comment]
I don't know. On the one hand looking at table 3? (Sample contents of the BathymetryCoverage and QualityOfSurvey arrays) it _appears_ to have only one attribute (that need appear in the feature catalogue), namely _id_.  On the other hand, perhaps the FC attributes should be those in _featureAttributeTable_ in Table 7? (Elements of featureAttributeTable compound datatype). On the third hand(!) some of the attributes in the latter table are in dotted form representing complex attributes, which, at the least, introduces additional complexities during validation and preparation of feature catalogues.

**Comment by rmalyankar** [comment]
To answer the specific question about 4.3.2 it should be included as a meta-feature. For resulting issues pertaining to its attributes, see my previous post. What are its attributes whcih should be described in 4.3.x, _id_ as specified in Table 3 (Sample contents...) or the attributes listed in featureAttributeTable (Table 7 - Elements of featureAttributeTable...)?

**Comment by rmalyankar** [comment]
Attributes for DCF 9:

1.  _bathyCoverage_ (Flag for  nodes  populated by interpolation) needs a new name, the registry already contains the concept _Bathymetric Coverage_ (Extent to which an area has been surveyed using a systematic method of measuring the depth and is based on the combination of the survey pattern and the theoretical area of detection of the survey instrumentation).

**Comment by hasel001** [comment]
Per decision in PT16, will be closed after @rmalyankar creates new issue as regards _bathyCoverage_.

**Comment by RohdeBSH** [comment]
Closing because issue #80 was created.
