### ISSUE TITLE
IHO Maritime Autonomous Surface Ships PT -- Request for Feedback -- by 12 February 2023

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#19]
[FI_S_102_IHOGapAnalysis.docx](https://docs.google.com/document/d/1KYP7g5PyoSA165C_jCp0UFOYnjmzEeLm/edit?usp=share_link&ouid=112418400259975980265&rtpof=true&sd=true)

Mr. Valtteri Laine is Finland's representative to the IHO Maritime Autonomous Surface Ships Project Team. They have conducted a gap analysis of S-102, and the linked file above describes their results. They have requested our PT to provide feedback on those results.

Please review the linked document and provide your comments here. My intent is for us to discuss/consolidate our comments during our 13 - 14 February VTC meeting and to forward our consensus results on 15 February. Please let me know if you have any questions or issues. Thank you!

Best regards,

Lawrence

**Comment by RohdeBSH** [comment]
Here is our (BSH) response. I have numbered the issues...

Issue 1:
We define the update cycle for bathymetric data based on our own regulations. This means that after the Nautical Information Service department of the BSH gets new bathymetric data, the product is ready to be distributed after a certain period.

Issue 2:
The file-size limit of 10 MB may need some discussion. It is not clear to us where this magic number comes from. Even with compression enabled, not all German S-102 products are below this limit (1-meter resolution). Perhaps the limit needs to be increased to 30 MB.

Issue 3:
Gaps are generally a problem.
The German sea area is quite small, but nevertheless a gapless coverage, is not a reasonable and desirable goal. At depths of more than 20 meters according to S-101, a gapless mapping of the seabed is no longer necessary. Sub-surface navigation is not within the remit of the BSH. The Issue is may linked to S-103 Sub-surface Navigation.
The problem must therefore be put into perspective. It is widely accepted that as long as the fairways and harbor areas are mapped without gaps, autonomous navigation should be possible.

Issue 4:
Unfortunately, the statement is not entirely correct. From raster data, features with certain properties can very well be automatically highlighted and converted into a vector representation. An example of this is the creation of contour lines from the raster data of the S-102. Thus, elevations and trenches can be detected very successfully. Smaller obstacles / anomalies can also be detected, for example, by calculating slopes in comparison to the neighboring pixels. There are enough algorithms available in general image processing to derive features from raster data. Another vector product in addition to S-101 and S-102 is therefore not necessary.

Issue 5:
This is exactly the reason why the new metadata coverage is introduced.

Issue 6:
No S-102 topic.

**Comment by tfilppula** [comment]
As I was involved in work on this document, I'd like to clarify the issue 4:
As @RohdeBSH wrote, it is of course possible to _derive_ vector features from raster data. However, Valtteri and the rest of us working at this document in the FIHO, were unanimous that this information should not be _stored_ in the S-102 products as S-102 is a raster product.
Another point of discussion was that as, to our understanding, S-102 is a navigation product meant for _surface navigation_ - even if it is suitable for subsurface operations too.

**Comment by CHS-LynnPatterson** [comment]
Gap issue 1) Speed and Frequency of updates - Concur with BSH, this is not an issue for the S-102, this is a data producer/distributor/distribution infrastructure issue associated with availability and frequency of updates being made available.

Gap issue 2) Communication infrastructure concerns with reliability and packet size. - The reliability of the communication infrastructure is not specific to the S-102 standard, however their concerns related to packet size are in direct correlation to the S-100WG's decision to put a cap on the S-101 product size of 10MB.    For Navigation I believe this is why we(S-102PT) followed suit at 10MB for an S-102 cell.

Gap Issue 3) Full coverage - Concur with BSH, Full coverage is not an S-102 issue.  At the end of the day hydrographic offices will determine where they have S-102 coverage or not.  S-102 makes sense in areas such as approaches to harbours,  shallow water ways,  harbours, and areas of great topographic change.  S-102 does not make sense in deep water, there the S-101 ENC would provide sufficient coverage for safe navigation.

Gap issue 4) More detailed seafloor topography and feature identification, concur with BSH -  for safe surface navigation the S-101 and S-102 will provide sufficient coverage to ensure safe navigation - disagree with the statement that this is a gap for the standards

Gap Issue 5)  Areas of  constant change in the topography such as high silting areas - Concur with BSH

Gap issue 6) the need to spatially enable information that is traditionally captured in descriptive text via Sailing directions, text boxes, or pick reports - if the descriptive text is not machine readable it cannot be processed by MASS.    Concur with BSH, this is not an S-102 spec issue, this is more the focus of S-101 and prod specs such as S-126 that will cover the traditional Sailing directions products.

**Comment by poseiron01** [comment]
We (SMA) have nothing to add. BSH and CHS has captured our thoughts very well.

**Comment by hasel001** [comment]
I would like to thank all the respondents for their comments. The consolidated form I am providing to Mr.  Valtteri Laine can be found here:

https://docs.google.com/document/d/1oJvi_a_rGXeUSbhx4qp5irPXbjUg_deA/edit?usp=share_link&ouid=112418400259975980265&rtpof=true&sd=true
