### ISSUE TITLE
Planning of S102PT meetings

### ISSUE THREAD

**Issue by giumas** [iho-ohi/S-102-Product-Specification#25]
Because of internal procedures, it would ease the attendance of future meetings that:

- The date of the meeting is known as soon as possible (no less than a couple of weeks) through the IHO Registration web page (https://online.iho-khoa.kr/registration). This becomes even more critical for meeting with physical attendance.
- A tentative agenda for the meeting is posted on the meeting webpage at least one week before the meeting.

**Comment by tfilppula** [comment]
Fully agree with @giumas. In our office it unfortunately takes quite a lot of time (=weeks) to get an OK for travel to face-to-face meetings. An invitation and agenda are also needed well before the actual meeting.
For VTC this does not apply, but of course it would be good to have an agenda and documents (if any) in advance.

**Comment by RohdeBSH** [comment]
Hello @hasel001,

If you have noted the discussion here, you can close the issue.
I think the requirements are correct in general. However, with respect to the first meeting in 2023, I can't quite understand it. Because the meeting was already announced with a date during the meeting in Monaco in December 2022. In any case, I had it in my calendar for quite a long time.

**Comment by giumas** [comment]
Hi @RohdeBSH,

What if a member was absent at the Monaco meeting? The date of the planned meetings should be publicly available.

**Comment by tfilppula** [comment]
Hi @RohdeBSH, @giumas, @hasel001,
I don't know if this only applies for our office at Traficom, but in our agency having only meeting date set is not sufficient to get an OK for travel.
In addition to set date, we also need an invitation and an agenda (draft will do) as early as possible.

**Comment by poseiron01** [comment]
Hi all! 
We at SMA also require an agenda well in advance to get an OK for travel.

**Comment by RohdeBSH** [comment]
Hi,

I agree with you. Basically, we also need an agenda. But with the S-1XX WG & PT it is different. An approximate knowledge of the topics is sufficient. For the S-102 we currently do not need an agenda at all, because the standard is considered essential and absolutely necessary.

REGARDS
Daniel

**Comment by giumas** [comment]
@RohdeBSH, I believe that a tentative agenda should give "an approximate knowledge of the topics". I would not know how to retrieve the topics otherwise.

**Comment by RohdeBSH** [comment]
What are we discussing here?
We are all in agreement.

A meeting must:
1. be agreed upon; entry in the meeting minutes or announced one month in advance.
2. there must be an entry for the meeting on the IHO web page.
3. an agenda must be available at least 2 weeks in advance. 
4. point 3. is also valid for proposals or longer documents (deadline for submission).

There must be rules for this at the IHO. We all know from experience that this is not the case. I have often been annoyed by very long English documents that are submitted the day before. So that then can be voted on it. An absolute disaster for all non-native speakers. But the IHO must solve this problem. 

In my opinion, we can be very happy that Lawrence organizes everything so well. I am sure that Lawrence will take note of your constructive criticism and pay more attention to it in the future. However, I see the main problem with the IHO.

**Comment by giumas** [comment]
> Basically, we also need an agenda. But with the S-1XX WG & PT it is different. An approximate knowledge of the topics is sufficient. 

@RohdeBSH, I asked for better understanding your point here. 
How can we retrieve an approximate knowledge of the topics for S-1XX WG & PT without a draft agenda? Based on the topics discussed in the previous meeting? On the open GitHub tickets?

**Comment by hasel001** [comment]
@giumas @tfilppula @poseiron01 @RohdeBSH I acknowledge that we need to continue being diligent about broadcasting meeting info well in advance of our meetings. With that said, would you concur with closing this issue?

**Comment by giumas** [comment]
I concur. Thanks for proposing it.
