### ISSUE TITLE
Clause 5.1 "association role"

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#53]
Clause 5.1, 2nd para:

>Note the vertical datum is defined through a second association role to a vertical reference system.

S-102 Edition 2.2.0 does not use association roles to indicate datums. Either:-
- delete the cited sentence, or
- revise it to say the vertical datum is specified separately in the root group attributes (or words to that effect).

**Comment by RohdeBSH** [comment]
I am for the second option

**Comment by HolgerBothien** [comment]
Another point, may not fit directly to this:
In table 8 for vertical Datum it says: 
Numeric code from IHO GI Registry Vertical Datum attribute except 

- 47 (seaFloor) 
- 48 (seaSurface) 
- 49 (hydrographicZero).

It would be better to have a positive list of values that are allowed instead of refering to a living docoment where every day new values can appear.

**Comment by rmalyankar** [comment]
I opened a new issue for this suggestion.

> Another point, may not fit directly to this: In table 8 for vertical Datum it says: Numeric code from IHO GI Registry Vertical Datum attribute except
> 
> * 47 (seaFloor)
> * 48 (seaSurface)
> * 49 (hydrographicZero).
> 
> It would be better to have a positive list of values that are allowed instead of refering to a living docoment where every day new values can appear.

**Comment by rmalyankar** [comment]
Since there are no further comments, I assume there are no obhection to the second choice.
Recommended substitute language: The vertical datum is specified separately using other root group attributes.

**Comment by hasel001** [comment]
I implemented the change as agreed in PT15. Thanks to all who participated in the work and the discussion!
