### ISSUE TITLE
Quality of formatting of the standard document

### ISSUE THREAD

**Issue by HolgerBothien** [iho-ohi/S-102-Product-Specification#57]
Though, the content is most important the formatting of an international standard should also follow some minimal requirements.
My observation with the version 2.2.0 as available from the IHO webpage is, that this requirements are not fully met.
This is off course my personal opinion but may be worth to be discussed. A few points:
1. The headings are using a thinner (and sometimes smaller) font than the plain text.
2. There should be an empty row above a heading line, I have observed headings directly under plain text or even under tables or figures.
3. The most annoying problem is the formatting of tables some columns are extremely small and line breaks appears in the middle of a word without hyphenation. 
In general I support the edition in an environment like Metanorma but the output must meet some basic requirements. 
I hope that the topics can be solved within the environment and the readability of the standard will be back to what it was before.

**Comment by RohdeBSH** [comment]
Generally, I support your statement. 
However, I think that this is an IHO/S-100 issue.

@hasel001 
I think we as PT should ask the IHO/S-100 to align the document appearance requirements with the Metanorma developers.

**Comment by ronaldtse** [comment]
@HolgerBothien as a representative from the Metanorma team we thank you for the feedback.

Can we clarify whether this is about HTML or PDF content?

> 1. The headings are using a thinner (and sometimes smaller) font than the plain text.

The "heading font" is never "smaller" in font size than body text.

It is however true that the heading font can be "thinner" in appearance than body text.

This is a design issue that we need to work together with @iho-ohi to address.

> 2. There should be an empty row above a heading line, I have observed headings directly under plain text or even under tables or figures.

While this used to be an issue, I'm not really seeing that in the latest generated document.

Could you please help screenshot examples so we can address this?

> 3. The most annoying problem is the formatting of tables some columns are extremely small and line breaks appears in the middle of a word without hyphenation.

Could we have examples on where this happens? I suspect that this is due to the width of tables not being able to fit on the page.

Metanorma PDF implements the HTML 4 table cell width balancing algorithm. So just like how when you shrink an HTML table in the browser to a width that can no longer accommodate the table's minimum width, the table contents will look broken. In this case, the solution is only either to re-do the table in a reasonable way (reduce columns, split tables, etc), or use "landscape mode" for that table.

**Comment by HolgerBothien** [comment]
> Could we have examples on where this happens? I suspect that this is due to the width of tables not being able to fit on the page.

Table 14 is an example. Landscape and smaller font size may help.

**Comment by rmalyankar** [comment]
References in S-102 Edition 3.0.0 use "sort-of" labels as well as numbers. The result is sometimes strange:

![Screenshot S102-3_0_0-References](https://github.com/user-attachments/assets/6b992dd1-6a9b-402c-953d-0e210f8cc08d)

IHO style is to use labels for references, not numbers.  Examples from S-101, S-104. (The examples from S-101 ought to include publisher and date information too. If there are authors listed in the publication, the authors' names should also be included.):

![Screenshot S101-1_4_1-References](https://github.com/user-attachments/assets/5b1964c2-8db0-46a1-845d-82d7250ce16b)

![Screenshot S104-2_0_0-References](https://github.com/user-attachments/assets/94bcd615-af71-40bb-b378-d17e6b81ab71)
