### ISSUE TITLE
 ISO metadata file clarification request

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-102-Product-Specification#69]
Issue #14  ISO metadata files says that the ISO metadata file is no longer needed for the navigational S-102.  

What value should be placed in the mandatory 'metadata' attribute that points to the ISO file.

![image](https://github.com/iho-ohi/S-102-Product-Specification/assets/50683133/f31429cc-bde9-4aed-b6ed-7fa36f739f6d)

**Comment by rmalyankar** [comment]
Since the attribute is still mandatory, the attribute should be encoded but as an empty 0-length string (preferable) or blank (space character(s) only.).

**Comment by giumas** [comment]
It sounds a bit weird that we have a mandatory attribute that can only be filled with an empty string. Should it be rather modified to be optional or even removed?

**Comment by TDYCARHugh** [comment]
I agree it should be optional but that field is defined in S-100 as mandatory so it would require a change to S-100.  If we agree what to use for a value until S-100 can be adjusted then we can go with that for now. I thought we should agree on something to be consistent and for validation checks to recognize.  Ok with empty string if it gets documented as acceptable.

**Comment by rmalyankar** [comment]
I have received a report from an implementor that they have problems creating an empty string for the "metadata" attribute for HDF5 format datasets in general and are therefore leaving it as one space (' ').  So I suggest that either the empty (0-length) string or blank (only space characters) string be documented as indicating that no metadata file is provided.

**Comment by rmalyankar** [comment]
A workaround to the implementor's issue appears to be feasible, so I am suspending my suggestion that "blank" strings also be allowed. (Meaning, I don't think "blank strings" will be necessary, but might revive the suggestion later if they can't get their workaround to work.)

**Comment by rmalyankar** [comment]
Draft S-100 maintenance proposal attached.
[Part 10c Metadata File Name.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/14069205/Part.10c.Metadata.File.Name.pdf)

**Comment by RohdeBSH** [comment]
> Draft S-100 maintenance proposal attached. [Part 10c Metadata File Name.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/14069205/Part.10c.Metadata.File.Name.pdf)

If the attribute becomes optional, do we no longer need to create the XML metadata file (S100_DatasetDiscoveryMetadata) in the future? Or will only the connection between HDF5 and XML metadata become optional and we still need to create the file (S100_DatasetDiscoveryMetadata)?
If Phase 1 products do not use XML metadata, why do non-Phase 1 products have to?
Do we still need the XML metadata (S100_DatasetDiscoveryMetadata) in the S-100?

The proposal does not yet consider the changes that would be necessary to the S-102. This was certainly not the intention, but should be taken into account in view of the short time available. Chapter 13 Metadata of the S-102 would need to be revised, as would the images. 
Furthermore, a correction (by the way, it is not called "correction" but "revision" [S-100 Ed. 5.1.0 Part 12 Section 12-2.2]; the IHO needs to update its documents again) for the S-100 Ed. 5.2.0 is no longer possible. The S-100 Ed. 5.2.0 has been approved by the S-100WG and will go into the approval process of the member states after the next HSSC meeting. The next S-100WG will not take place until after the HSSC meeting, i.e. in November 2024. The proposal can only be submitted at this S-100 WG meeting. A "correction"/revision requires mandatory approval by the member states, according to S-100 Ed. 5.1.0 Part 12 Section 12-2.2. As sorry as I am, I don't see any possibility of incorporating this into S-100 Ed. 5.2.0 with the current process and the current time frame. It is therefore more a topic for the backlog of S-100 Ed. 6.0.0.
It's a sad thing really, if we no longer had to write the metadata (S100_DatasetDiscoveryMetadata), that would be a great help.

Or...
Am I on the wrong track?

**Comment by RohdeBSH** [comment]
While I was having my first tea, I thought about it again.
The proposal is addressed to the TSM. From my point of view, however, it is not a TSM issue and should therefore be addressed to the S-100WG.
This is purely a content issue. The technical way in which it should work is clear and is already included in the S-100. In my view, there is no reason to bypass the S-100WG as the first instance. Only the S-100WG can decide on the approval/rejection of the proposal. I don't think it's correct to submit proposals directly to the TSM. First, the S-100WG should form an opinion and if this is not clear, it should be referred to the TSM for advice.

**Comment by giumas** [comment]
> Do we still need the XML metadata (S100_DatasetDiscoveryMetadata) in the  S-100?

I believe that this @RohdeBSH's question is critical here. Should the proposal be modified to propose the deletion or, if necessary for specific products, the change to be optional? The idea would be to trigger the discussion on whether there is a foreseen need for this kind of metadata file.

**Comment by rmalyankar** [comment]
S-100 TSMs are an appropriate venue for discussing S-100 maintenance proposals before they are submitted to the full S-100 WG for further discussions and decisions.

However, the time for the forthcoming (March 2024) TSM is likely to be all taken up with S-164, validation, and S-98 matters, so it is likely that a non-critical S-100 proposal like this one will be postponed to the next S-100 working group anyway. Which would be OK as far as I am concerned.

To @giumas  question about deleting it instead of making it optional (presumably removing if from S-100 Part 10c) I recollect that at an S-102 VTC for a previous edition of S-102 there was a discussion that ended up in a tie about whether ISO metadata should be provided...so I suggest having that discussion when we all have more leisure and a better grasp of use cases including potential MSDI use cases for the non-navigation product.

**Comment by rmalyankar** [comment]
Holger mentioned this during the meeting, but for the record, the ISO metadata file and S-100 discovery metadata are different things.

**Comment by RohdeBSH** [comment]
I know that @rmalyankar 's proposal was approved at the TSM-10 meeting.
But my problem now is that the changes are not included in S-100 5.2.0.
Theoretically it is not possible, because with the S-100WG Letter3/2023 corresponding S-100 5.2.0 versions with review until January 19, 2024 were sent out. Email from Yong dated December 19, 2023.
However, TSM-10 did take place in March 2024, long after the S-100WG had adopted S-100 5.2.0.
As a member of the S-100WG, I have not received any indication of a subsequent change to this day.

Current changes in S-100 5.2.0 according to S-100WG L3/2023: http://portal.iho.int/share/files/1633
Latest drafts: https://iho.int/en/draft-publications

Hence, the question, what is the status of the proposal?
In my opinion, I currently have to create the metadata file (MD_???.XML), as I have to make a corresponding entry in the HDF5 file.

**Comment by rmalyankar** [comment]
S-100 Edition 5.2.0 has now been published and the change to the multiplicity of the _metadata_ attribute has been applied. This attribute is optional in S-100 Edition 5.2.0.

**Comment by hasel001** [comment]
It was remarked during S-102PT19 that the aforementioned publication of S-100 Ed. 5.2.0 has effectively resolved this issue. I am marking it closed.
