### ISSUE TITLE
Common point rule: limit allowed values?

### ISSUE THREAD

**Issue by tfilppula** [iho-ohi/S-102-Product-Specification#74]
The attribute _commonPointRule_ (Table 11 in PS) is used for evaluating the coverage at a position that falls on the boundary between geometric objects in the domain of the coverage. Currently the following values are allowed (S-100 ed. 5.0.0):

![image](https://github.com/iho-ohi/S-102-Product-Specification/assets/13709365/b2c513d7-d731-4a62-8f50-1edad74f2775)

Since we're talking about a navigation product and safety comes first: should we allow only the value 2 to be used?

**Comment by AnnaWall01** [comment]
SMA will only use value '2', for the reason the Topi mentions regarding safety of navigation.

**Comment by RohdeBSH** [comment]
I don't think it's that relevant.
When I make a depth query in a grid, it always happens with an XY coordinate. So I hit exactly one grid cell with exactly one depth value, or no grid cell at all. The commonPointRule is therefore not used at all, because only one depth value is returned, not several.
The situation is different if I request the depth using a bounding box. Then many depth values can be returned. The commonPointRule then helps me to select the correct one.
However, I do not see this use case with the S-102.
Nevertheless, the value 2 (low) is the more correct value. As Topi has already mentioned.
However, the CommonPointRule depends on the direction of the z-axis. In the case of the S-102, where the positive z-axis points to the center of the earth, it must therefore be 2 (low) in order to be nautically safe.

**Comment by tfilppula** [comment]
I beg to differ.
You can query a grid at exactly at border of two (or three or four) grid cells containing data. If this happens, you have several nearest neighbours, so which one to report? I think the shoalest value makes most sense.

**Comment by tfilppula** [comment]
In the S-102PT16 meeting this proposal was accepted and it was decided that this change is included in the pull request #73 
The change has been made and this issue will be closed when the pull request is merged.
