### ISSUE TITLE
S100 - Mandatory Attribute - TimePoint - Guidance

### ISSUE THREAD

**Issue by RohdeBSH** [iho-ohi/S-102-Product-Specification#86]
In S-100 ed 5.1.0 and I think in 5.2.0 also there is an attribute called "timePoint". This attribute is mandatory for Data Coding Format 1, 2, 3, 4, 5, 6 and 7. See S-100 ed. 5.1.0 Table 10c-19 – Attributes of values groups.

BSH is asking the group for guidance on what the attribute should represent. 
It is a timestamp, but the timestamp of what?
File creation time?
Issue timestamp?

Does anyone have an idea? I'm asking because I couldn't find any guidance in S-102.

**Comment by RohdeBSH** [comment]
Confirmed: The attribute is mandatory in S-100 ed. 5.2.0 also.

**Comment by tfilppula** [comment]
In S-100 ed. 4.0.0 this was an _optional_  attribute for time series data. Somehow it made it's way to 5.2.0 as mandatory.

![Capture](https://github.com/iho-ohi/S-102-Product-Specification/assets/13709365/aa8e882c-0823-4336-aee3-9ae913db3f4a)

**Comment by hasel001** [comment]
I spoke with Greg Seroka who authored the paper that made timePoint become mandatory.

1. He suggests that, for S-102:
  a. For data from single bathymetric surveys, it could represent the acquisition time for that survey.
  b. For data from multiple acquisition times (or where otherwise necessary), the fillValue 00010101T000000Z could be used (to be consistent with S-104 and S-111 uses).

2. He mentioned later (after discussion with @rmalyankar) that timePoint should probably be reverted back to optional in a future edition of S-100. He further clarified that the intent of the proposal was merely to add DCF=8 (and was not to limit optionality).

Given the above information,

3. Should we add any guidance (from 1) to *11.2.6 The values group -- Group_001*?

4. I will take for action to reach out to Greg and Jeff Wootton regarding the particulars of a proposal to S-100 to revert it to optional. (As it stands, the row defining its multiplicity applies to DCF [1-7]. The complete solution, for example, might involve it becoming optional for DCF=2 but remaining mandatory for others, and I want to fully explore that before proposing anything.)

**Comment by RohdeBSH** [comment]
We have a different method (QualityOfBathymertryCoverage) for specifying the survey date within an S-102 product. We should not deviate from this even if there is only one survey within an S-102 product. Treating the survey date differently in a special case could lead to confusion. In addition, the OEM would have to implement a special solution.

So the only way is to always write a default date. 

By the way, Germany writes the creation time of the file in this field. This can be different from issueDate and issueTime. This adds at least one useful piece of information to the field.

**Comment by rmalyankar** [comment]
If S-102 does not need the _timePoint_ field it should be populated with the fill value instead. Note that _timePoint_ is at the _values group_ level, it is metadata for each values group.

**Comment by hasel001** [comment]
I made the change [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/59cbd379a5c0c660c9bc51dcc9b975cf6754e1eb). Thank all 3 of you for your help! I am marking the issue closed.
